"use client";
import { useState } from "react";
type Bed = { id:string; name:string; emoji:string; x:number;y:number;w:number;h:number; color:string; notes:string };
const initial:Bed[]=[
{id:"flowers",name:"Flowers",emoji:"🌸",x:18,y:2,w:79,h:11,color:"#b74b79",notes:"Flower border along the back."},
{id:"herbs",name:"Herbs",emoji:"🌿",x:2,y:16,w:13,h:78,color:"#397c44",notes:"Long herb border on the left."},
{id:"garlic",name:"Garlic",emoji:"🧄",x:25,y:20,w:18,h:26,color:"#639c53",notes:"After harvesting garlic: broccoli seedlings, then lettuce."},
{id:"green-peppers",name:"Green Peppers",emoji:"🫑",x:48,y:20,w:18,h:26,color:"#348c3e",notes:"Green bell peppers."},
{id:"okra",name:"Okra",emoji:"🌱",x:75,y:20,w:21,h:26,color:"#4b8640",notes:"Warm-season okra."},
{id:"tomatoes-left",name:"Tomatoes",emoji:"🍅",x:22,y:55,w:22,h:24,color:"#477f39",notes:"First tomato bed."},
{id:"tomatoes-middle",name:"Tomatoes",emoji:"🍅",x:48,y:55,w:18,h:37,color:"#477f39",notes:"Second tomato bed."},
{id:"hot-peppers-right",name:"Hot Peppers",emoji:"🌶️",x:76,y:53,w:20,h:20,color:"#447e3b",notes:"Hot peppers."},
{id:"hot-peppers-bottom",name:"Hot Peppers",emoji:"🌶️",x:70,y:79,w:28,h:16,color:"#447e3b",notes:"Second hot pepper bed."},
];
function GardenBedArt({bed}:{bed:Bed}){
 const flowers=bed.id==="flowers", herbs=bed.id==="herbs", garlic=bed.id==="garlic";
 const count=flowers?38:herbs?30:bed.id==="okra"?18:24;
 const palette=flowers?["#e89db4","#f6c2c9","#dc6e96","#fff1d7"]:["#3b8045","#75ad55","#a2c478","#295d36"];
 return <svg viewBox="0 0 200 160" preserveAspectRatio="xMidYMid slice" className="absolute inset-0 h-full w-full" aria-hidden="true">
 <defs><pattern id={`soil-${bed.id}`} width="17" height="17" patternUnits="userSpaceOnUse"><rect width="17" height="17" fill="#46382a"/><circle cx="4" cy="5" r="1.5" fill="#67503a"/><circle cx="12" cy="13" r="1" fill="#776044"/></pattern><radialGradient id={`leaf-${bed.id}`}><stop stopColor="#a5ce7e"/><stop offset="1" stopColor="#326d39"/></radialGradient></defs>
 <rect width="200" height="160" fill={`url(#soil-${bed.id})`}/>
 {Array.from({length:count},(_,i)=>{const x=12+(i%7)*29+((i*7)%9),y=12+Math.floor(i/7)*(flowers?27:35)+((i*11)%13),s=flowers?0.72:herbs?0.85:garlic?0.65:1.05;return <g key={i} transform={`translate(${x} ${y}) scale(${s}) rotate(${(i*37)%70-35})`}>
 <path d="M0 14V-13" stroke="#4a7939" strokeWidth="2.8"/><ellipse cx="-9" cy="-6" rx="11" ry="6" fill={`url(#leaf-${bed.id})`} transform="rotate(30 -9 -6)"/><ellipse cx="9" cy="-8" rx="11" ry="6" fill={palette[i%palette.length]} transform="rotate(-30 9 -8)"/><ellipse cx="0" cy="-15" rx="6" ry="12" fill="#699e4d"/>
 {flowers?<g><circle r="7.5" cy="-10" fill={palette[i%4]}/><circle cx="-6" cy="-13" r="5" fill={palette[i%4]}/><circle cx="6" cy="-13" r="5" fill={palette[i%4]}/><circle cx="0" cy="-10" r="3" fill="#e9bc55"/></g>:bed.id.includes("tomatoes")?<circle cx="7" cy="3" r="5" fill="#c74831"/>:bed.id.includes("peppers")?<ellipse cx="7" cy="5" rx="4" ry="7" fill={bed.id==="green-peppers"?"#71a643":"#c95635"}/>:null}
 </g>})}</svg>;
}
export default function GardenLayout({userId,gardenId,onClose}:{userId:string;gardenId:string;onClose:()=>void}){
 const storageKey=`garden-os-layout-2027-${userId}-${gardenId}`;
 const [beds,setBeds]=useState<Bed[]>(()=>{if(typeof window==="undefined")return initial;try{const saved=JSON.parse(localStorage.getItem(storageKey)||"null");return Array.isArray(saved)&&saved.length?saved:initial;}catch{return initial;}});
 const [photoReady,setPhotoReady]=useState(false); const [selected,setSelected]=useState("garlic"); const [editing,setEditing]=useState(false); const [notice,setNotice]=useState(""); const [view,setView]=useState<"garden"|"plan">("garden");
 const active=beds.find(b=>b.id===selected);
 function update(next:Bed[]){setBeds(next);try{localStorage.setItem(storageKey,JSON.stringify(next));setNotice("Layout saved on this browser.");}catch{setNotice("Storage unavailable; layout is only saved for this visit.");}}
 function change(field:keyof Bed,value:string){if(!active)return;update(beds.map(b=>b.id===active.id?{...b,[field]:["x","y","w","h"].includes(field)?Number(value):value}:b));}
 function addBed(){const id=`bed-${Date.now()}`;update([...beds,{id,name:"New Bed",emoji:"🌱",x:30,y:35,w:17,h:16,color:"#477f39",notes:"Add planting notes here."}]);setSelected(id);setEditing(true);}
 function removeBed(){if(!active||!window.confirm(`Delete ${active.name} from this layout?`))return;update(beds.filter(b=>b.id!==active.id));setSelected(beds.find(b=>b.id!==active.id)?.id||"");}
 return <section className="mt-8">
 <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="rounded-2xl bg-[#e9d7bd] p-4 text-4xl shadow-sm" aria-hidden="true">🪴</div><div><h2 className="editorial-title seasonal-heading text-4xl">Garden Layout</h2><p className="seasonal-muted mt-1">Plan, visualize, and manage your 2027 garden beds.</p></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setView("garden")} aria-pressed={view==="garden"} className={`rounded-xl px-4 py-3 font-semibold ${view==="garden"?"bg-[#9a4a1b] text-white":"seasonal-outline border"}`}>Garden View</button><button onClick={()=>setView("plan")} aria-pressed={view==="plan"} className={`rounded-xl px-4 py-3 font-semibold ${view==="plan"?"bg-[#9a4a1b] text-white":"seasonal-outline border"}`}>Plan View</button><button onClick={addBed} className="seasonal-outline rounded-xl border px-4 py-3 font-semibold">＋ Add Bed</button><button onClick={()=>setEditing(!editing)} className="seasonal-outline rounded-xl border px-4 py-3 font-semibold">{editing?"Done editing":"✎ Edit Layout"}</button><button onClick={onClose} className="seasonal-outline rounded-xl border px-4 py-3 font-semibold">← Back</button></div></div>
 <div className="mt-6 grid gap-4 xl:grid-cols-[190px_minmax(0,1fr)_290px]">
 <nav aria-label="Garden layout sections" className="seasonal-card h-fit rounded-2xl border p-3"><p className="rounded-lg bg-[#f1e3d0] px-3 py-3 font-bold text-[#844219]">▣ Garden Layout</p><p className="seasonal-muted mt-5 px-2 text-xs font-bold uppercase tracking-wider">Beds in my garden</p><div className="mt-2 space-y-1">{beds.map(b=><button key={b.id} onClick={()=>setSelected(b.id)} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${selected===b.id?"bg-[#ead6b9] font-bold text-[#553b25]":"hover:bg-[#eee6d9]"}`}>{b.emoji} {b.name}</button>)}</div></nav>
 <div className="overflow-hidden rounded-2xl border border-[#b49b76] bg-[#9b8465] shadow-xl">
 <div className="relative aspect-[990/841] w-full overflow-hidden" style={{background:view==="garden"?"repeating-linear-gradient(27deg,#a88c64 0px,#a88c64 3px,#c1a47c 4px,#a98b64 12px)":"linear-gradient(135deg,#d7e5c7,#b6c9a4)"}}>
 {view==="garden"&&<img src="/garden-layout-2027.webp" alt="Photorealistic overhead view of the 2027 garden, with flower and herb borders, garlic, green peppers, okra, tomatoes and hot peppers" className="absolute inset-0 h-full w-full object-fill" onLoad={()=>setPhotoReady(true)} onError={()=>setPhotoReady(false)}/>}
 {beds.map(b=><button type="button" key={b.id} onClick={()=>setSelected(b.id)} aria-label={`Select ${b.name}`} className={`group absolute overflow-hidden text-center transition-all hover:brightness-110 focus-visible:outline focus-visible:outline-4 focus-visible:outline-amber-200 ${view==="garden"?"border-2 border-transparent bg-transparent hover:border-amber-200/80": "border-[7px] shadow-[3px_7px_14px_#2d211b80]"} ${selected===b.id?"ring-4 ring-[#f7df9b] ring-offset-2 ring-offset-[#8b7758]":""}`} style={{left:`${b.x}%`,top:`${b.y}%`,width:`${b.w}%`,height:`${b.h}%`,borderColor:view==="garden"?"transparent":"#6b8962",borderRadius:b.id==="flowers"?"55px":b.id==="herbs"?"40px":b.id.includes("bottom")?"32px":"12px",background:view==="garden"?"transparent":"#486f3b",boxShadow:view==="garden"?"none":"inset 0 0 0 3px #c39a66, 3px 7px 14px #2d211b80"}}>
 {view==="garden"?(photoReady?null:<GardenBedArt bed={b}/>):<div className="absolute inset-0" style={{background:`repeating-linear-gradient(45deg,${b.color},${b.color} 14px,#ffffff22 15px,#ffffff22 16px)`}}/>}
 {(view==="plan"||!photoReady)&&<span className="absolute bottom-1 left-1/2 max-w-[95%] -translate-x-1/2 rounded-lg bg-[#fff8e9ef] px-2 py-1 text-[clamp(9px,1.2vw,13px)] font-bold leading-tight text-[#3e3326] shadow">{b.emoji} {b.name}</span>}
 </button>)}
 </div><div className="bg-[#f4e9d6] px-4 py-3 text-xs text-[#67523a]">{view==="garden"?(photoReady?"Photorealistic overhead garden (interactive bed hotspots)":"Illustrated garden preview — photo asset not yet installed"):"Simplified planning view"} · Approximate placement, not measured to scale</div></div>
 <aside className="seasonal-card h-fit rounded-2xl border p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-bold seasonal-heading">Bed Details</h3><button onClick={()=>setSelected("")} aria-label="Close bed details" className="seasonal-muted text-xl">×</button></div>{active?<><div className="mt-4 overflow-hidden rounded-xl bg-[#e2e7d5]"><div className="relative h-36"><GardenBedArt bed={active}/></div></div><div className="mt-4 flex items-center justify-between"><h4 className="seasonal-heading text-2xl font-bold">{active.emoji} {active.name}</h4><button onClick={()=>setEditing(true)} className="seasonal-outline rounded-lg border px-3 py-1 text-sm">Edit</button></div><p className="seasonal-muted mt-4 text-sm leading-6">{active.notes}</p><div className="mt-5 divide-y text-sm"><div className="flex justify-between gap-3 py-3"><span className="seasonal-muted">Garden year</span><strong>2027</strong></div><div className="flex justify-between gap-3 py-3"><span className="seasonal-muted">Map position</span><span>{active.x}%, {active.y}%</span></div><div className="flex justify-between gap-3 py-3"><span className="seasonal-muted">Map footprint</span><span>{active.w}% × {active.h}%</span></div></div>{active.id==="garlic"&&<div className="mt-5 rounded-xl bg-[#f6efe3] p-3 text-sm text-[#473b2e]"><strong>Succession plan</strong><p className="mt-2">🧄 Garlic → 🥦 Broccoli seedlings → 🥬 Lettuce</p></div>}{editing&&<div className="mt-4 space-y-3"><label className="block text-sm font-semibold">Bed name<input value={active.name} onChange={e=>change("name",e.target.value)} className="seasonal-input mt-1 w-full rounded-xl border p-2"/></label><label className="block text-sm font-semibold">Notes<textarea value={active.notes} onChange={e=>change("notes",e.target.value)} className="seasonal-input mt-1 w-full rounded-xl border p-2" rows={3}/></label><p className="text-xs seasonal-muted">Map coordinates and size (percent)</p>{(["x","y","w","h"] as const).map(field=><label key={field} className="flex items-center justify-between gap-3 text-sm"><span>{field.toUpperCase()}</span><input type="number" min="1" max="99" value={active[field]} onChange={e=>change(field,String(Math.max(1,Math.min(99,Number(e.target.value)))))} className="seasonal-input w-20 rounded-lg border p-2"/></label>)}</div>}<button onClick={removeBed} className="mt-6 w-full rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">Delete Bed</button></>:<p className="seasonal-muted mt-5 text-sm">Select a bed to view its details.</p>}{notice&&<p role="status" className="seasonal-muted mt-4 text-xs">{notice}</p>}<p className="seasonal-muted mt-6 border-t pt-4 text-xs leading-5">Layout edits are saved in this browser only. Your existing garden and growing-space records are not changed.</p></aside></div></section>;
}
